spring:
  thymeleaf:
    cache: false # true: web-page is cached, false: web-page will render on every change (good for development)
    prefix: file:src/main/resources/templates/ #directly serve from src folder instead of target
auth:
  api_key: ${API_KEY}   # put your own API key here or use DEMO_KEY